// YouTube Transcript Extractor
// Uses InnerTube /player API → captionTracks → /api/timedtext (same approach as yt-dlp)

// --- Types ---

export interface TranscriptSegment {
  startMs: number;
  endMs: number;
  text: string;
}

export interface Language {
  code: string;
  name: string;
  isAutoGenerated: boolean;
}

export type TranscriptResult = TranscriptSegment[] | string;

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string; runs?: { text: string }[] };
  vssId?: string;
  isTranslatable?: boolean;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: { utf8?: string }[];
}

// --- Constants (from yt-dlp INNERTUBE_CLIENTS.ios) ---

const IOS_CONTEXT = {
  client: {
    clientName: "IOS",
    clientVersion: "21.02.3",
    deviceMake: "Apple",
    deviceModel: "iPhone16,2",
    userAgent: "com.google.ios.youtube/21.02.3 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X;)",
    osName: "iPhone",
    osVersion: "18.3.2.22D82",
  },
} as const;

const USER_AGENT = IOS_CONTEXT.client.userAgent;
const PLAYER_URL = "https://www.youtube.com/youtubei/v1/player?prettyPrint=false";

// --- Helpers ---

function extractTrackName(track: CaptionTrack): string {
  if (track.name?.simpleText) return track.name.simpleText;
  if (track.name?.runs) return track.name.runs.map((r) => r.text).join("");
  return track.languageCode;
}

function getLangCode(track: CaptionTrack): string {
  if (track.vssId) {
    return track.vssId.replace(/^\./, "").replace(/\./g, "-");
  }
  return track.languageCode;
}

function parseVideoId(input: string): string {
  // Accept full URLs or plain video IDs
  try {
    const url = new URL(input);
    if (url.hostname === "youtu.be") return url.pathname.slice(1);
    return url.searchParams.get("v") || input;
  } catch {
    return input;
  }
}

function formatTimestamp(ms: number, separator: string): string {
  const totalSeconds = Math.floor(ms / 1000);
  const h = Math.floor(totalSeconds / 3600);
  const m = Math.floor((totalSeconds % 3600) / 60);
  const s = totalSeconds % 60;
  const millis = ms % 1000;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}${separator}${String(millis).padStart(3, "0")}`;
}

// --- Core Functions ---

async function fetchPlayerResponse(videoId: string): Promise<Record<string, unknown>> {
  const body = {
    context: IOS_CONTEXT,
    videoId,
  };

  const res = await fetch(PLAYER_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": USER_AGENT,
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    throw new Error(`InnerTube player request failed: ${res.status} ${res.statusText}`);
  }

  return res.json() as Promise<Record<string, unknown>>;
}

function extractCaptionTracks(playerResponse: Record<string, unknown>): CaptionTrack[] {
  const captions = playerResponse.captions as Record<string, unknown> | undefined;
  if (!captions) return [];

  const renderer = captions.playerCaptionsTracklistRenderer as Record<string, unknown> | undefined;
  if (!renderer) return [];

  return (renderer.captionTracks as CaptionTrack[] | undefined) ?? [];
}

async function fetchTimedText(baseUrl: string): Promise<TranscriptSegment[]> {
  // Append fmt=json3 and xosf= (empty to skip position data, per yt-dlp #13654)
  const url = new URL(baseUrl);
  url.searchParams.set("fmt", "json3");
  url.searchParams.set("xosf", "");

  const res = await fetch(url.toString(), {
    headers: { "User-Agent": USER_AGENT },
  });

  if (!res.ok) {
    throw new Error(`Timedtext fetch failed: ${res.status} ${res.statusText}`);
  }

  const data = (await res.json()) as { events?: Json3Event[] };
  const events = data.events ?? [];

  const segments: TranscriptSegment[] = [];
  for (const event of events) {
    if (!event.segs) continue;

    const text = event.segs
      .map((seg) => seg.utf8 ?? "")
      .join("")
      .trim();
    if (!text) continue;

    const startMs = event.tStartMs ?? 0;
    const durationMs = event.dDurationMs ?? 0;

    segments.push({
      startMs,
      endMs: startMs + durationMs,
      text,
    });
  }

  return segments;
}

// --- Formatters ---

function toSRT(segments: TranscriptSegment[]): string {
  return segments
    .map((seg, i) => {
      const start = formatTimestamp(seg.startMs, ",");
      const end = formatTimestamp(seg.endMs, ",");
      return `${i + 1}\n${start} --> ${end}\n${seg.text}`;
    })
    .join("\n\n");
}

function toVTT(segments: TranscriptSegment[]): string {
  const cues = segments
    .map((seg) => {
      const start = formatTimestamp(seg.startMs, ".");
      const end = formatTimestamp(seg.endMs, ".");
      return `${start} --> ${end}\n${seg.text}`;
    })
    .join("\n\n");

  return `WEBVTT\n\n${cues}`;
}

// --- Public API ---

export async function listTranscriptLanguages(videoId: string): Promise<Language[]> {
  const id = parseVideoId(videoId);
  const playerResponse = await fetchPlayerResponse(id);
  const tracks = extractCaptionTracks(playerResponse);

  return tracks.map((track) => {
    const isAuto = track.kind === "asr";
    let name = extractTrackName(track);
    if (isAuto) name = name.replace(/\s*\(auto-generated\)\s*$/i, "");
    return { code: getLangCode(track), name, isAutoGenerated: isAuto };
  });
}

export async function getTranscript(
  videoId: string,
  options?: { lang?: string; format?: "json" | "srt" | "vtt" },
): Promise<TranscriptResult> {
  const id = parseVideoId(videoId);
  const format = options?.format ?? "json";

  const playerResponse = await fetchPlayerResponse(id);
  const tracks = extractCaptionTracks(playerResponse);

  if (tracks.length === 0) {
    throw new Error("No captions available for this video");
  }

  // Find requested language or use first available
  let track: CaptionTrack | undefined;
  if (options?.lang) {
    track = tracks.find(
      (t) => getLangCode(t) === options.lang || t.languageCode === options.lang,
    );
    if (!track) {
      const available = tracks.map((t) => getLangCode(t)).join(", ");
      throw new Error(`Language "${options.lang}" not found. Available: ${available}`);
    }
  } else {
    track = tracks[0];
  }

  const segments = await fetchTimedText(track.baseUrl);

  switch (format) {
    case "srt":
      return toSRT(segments);
    case "vtt":
      return toVTT(segments);
    default:
      return segments;
  }
}

// --- CLI ---

async function main() {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.log("Usage: bun run yt-transcript.ts <video-id-or-url> [--lang <code>] [--format json|srt|vtt] [--list]");
    process.exit(1);
  }

  const videoInput = args[0];
  const langIdx = args.indexOf("--lang");
  const fmtIdx = args.indexOf("--format");
  const listMode = args.includes("--list");

  const lang = langIdx !== -1 ? args[langIdx + 1] : undefined;
  const format = (fmtIdx !== -1 ? args[fmtIdx + 1] : "json") as "json" | "srt" | "vtt";

  if (listMode) {
    const languages = await listTranscriptLanguages(videoInput);
    console.log("Available languages:");
    for (const l of languages) {
      console.log(`  ${l.code} — ${l.name}${l.isAutoGenerated ? " (auto-generated)" : ""}`);
    }
    return;
  }

  const result = await getTranscript(videoInput, { lang, format });

  if (typeof result === "string") {
    console.log(result);
  } else {
    console.log(JSON.stringify(result, null, 2));
  }
}

main().catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
